### PR TITLE
CSV Header in Export

### PR DESCRIPTION
**Pull request by edesilets**
This feature will allow users when exporting datasets to be able to request the CSV file header.

### CODE REVIEW

**Comment by edesilets** [comment]
@woganmay do you have time to look this pull request over?

**Comment by woganmay** [comment]
@edesilets I do now!

**Review by woganmay — APPROVED** [review]

**Comment by edesilets** [comment]
Awesome @woganmay thanks so much!

**Comment by woganmay** [comment]
No problem @edesilets , just a heads up: I'm about a day away from pushing a big update to this repo, to include all the new API endpoints since this project was released. There's definitely gonna be a few breaking changes.

**Comment by edesilets** [comment]
Ok sounds good! Thanks for the heads up!

**Pull request merged**
